version: 2.1

workflows:
  version: 2
  all-checks:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/node:16.20.0
    steps:
      - run:
          name: Install buf
          command: |
            wget -O buf "https://github.com/bufbuild/buf/releases/download/v1.16.0/buf-$(uname -s)-$(uname -m)"
            chmod +x buf
            sudo mv buf /usr/local/bin
            buf --version
      - checkout
      - run:
          name: Checkout submodules
          command: git submodule init && git submodule update
      - run:
          name: Version information
          command: echo "node $(node --version)"; echo "npm $(npm --version)"
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Generate code (.proto -> .ts)
          command: npm run codegen
      - run:
          name: Ensure schemas are up-to-date
          command: |
            CHANGES_IN_REPO=$(git status --porcelain)
            if [[ -n "$CHANGES_IN_REPO" ]]; then
              echo "Repository is dirty. Showing 'git status' and 'git --no-pager diff' for debugging now:"
              git status && git --no-pager diff
              exit 1
            fi
      - run:
          name: Build (.ts -> .js/.d.ts)
          command: npm run build
